import Vue from 'vue'
import {
  Tab,
  Tabs,
  Swipe,
  SwipeItem,
  NavBar,
  Icon,
  search,
  Sticky,
  IndexBar,
  IndexAnchor,
  List,
  slider,
  progress,
  PullRefresh,
  Loading,
  Toast,
  Dialog,
  Lazyload,
  Field,
  CellGroup,
  Button,
  CountDown,
  ActionSheet,
  Circle,
  Popup,
  Image,
  Overlay
} from 'vant'
Vue.use(Tab)
Vue.use(Tabs)
Vue.use(Swipe)
Vue.use(SwipeItem)
Vue.use(NavBar)
Vue.use(Icon)
Vue.use(search)
Vue.use(Sticky)
Vue.use(IndexBar)
Vue.use(IndexAnchor)
Vue.use(List)
Vue.use(slider)
Vue.use(progress)
Vue.use(PullRefresh)
Vue.use(Loading)
Vue.use(Toast)
Vue.use(Dialog)
Vue.use(Lazyload)
Vue.use(Field)
Vue.use(CellGroup)
Vue.use(Button)
Vue.use(CountDown)
Vue.use(ActionSheet)
Vue.use(Circle)
Vue.use(Popup)
Vue.use(Image)
Vue.use(Overlay)
Vue.prototype.$Dialog = Dialog
Vue.prototype.$toast = Toast
